In [1]:
!pip install pandas numpy scikit-learn tensorflow keras matplotlib seaborn

Requirement already satisfied: pandas in c:\users\sujph\.conda\envs\myenv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\sujph\.conda\envs\myenv\lib\site-packages (2.0.2)
Requirement already satisfied: scikit-learn in c:\users\sujph\.conda\envs\myenv\lib\site-packages (1.6.1)
Requirement already satisfied: tensorflow in c:\users\sujph\.conda\envs\myenv\lib\site-packages (2.18.0)
Requirement already satisfied: keras in c:\users\sujph\.conda\envs\myenv\lib\site-packages (3.8.0)
Requirement already satisfied: matplotlib in c:\users\sujph\.conda\envs\myenv\lib\site-packages (3.9.4)
Requirement already satisfied: seaborn in c:\users\sujph\.conda\envs\myenv\lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: tensorflow-intel==2.18.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow) (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (5.29.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (75.8.0)
Requirement already satisfied: six>=1.12.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.70.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.18.0)
Requirement already satisfied: h5py>=3.11.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.13.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.31.0)
Requirement already satisfied: rich in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from keras) (13.9.4)
Requirement already satisfied: namex in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from keras) (0.0.8)
Requirement already satisfied: optree in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from keras) (0.14.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: pillow>=8 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: zipp>=3.1.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from importlib-resources>=3.2.0->matplotlib) (3.21.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from rich->keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from rich->keras) (2.15.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.18.0->tensorflow) (0.45.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2025.1.31)
Requirement already satisfied: markdown>=2.6.8 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.1.3)
Requirement already satisfied: importlib-metadata>=4.4 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from markdown>=2.6.8->tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (8.5.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.0.2)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import tensorflow as tf
from tensorflow import keras

In [3]:
import pandas as pd

# Define column names as per NSL-KDD dataset
columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
           'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in',
           'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
           'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 'is_guest_login',
           'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate',
           'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
           'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
           'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
           'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'attack', 'level']

# Load dataset
df = pd.read_csv("KDDTrain+.txt", names=columns)

# Display first five rows
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,level
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [4]:
# Display dataset shape
print(f"Dataset shape: {df.shape}")

# Check data types and missing values
print(df.info())

# Show unique attack types
print(f"Unique attack types:\n{df['attack'].unique()}")

Dataset shape: (125973, 43)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     125973 non-null  int64
 1   protocol_type                125973 non-null  object
 2   service                      125973 non-null  object
 3   flag                         125973 non-null  object
 4   src_bytes                    125973 non-null  int64
 5   dst_bytes                    125973 non-null  int64
 6   land                         125973 non-null  int64
 7   wrong_fragment               125973 non-null  int64
 8   urgent                       125973 non-null  int64
 9   hot                          125973 non-null  int64
 10  num_failed_logins            125973 non-null  int64
 11  logged_in                    125973 non-null  int64
 12  num_compromised              125973 non-null  int64
 13  root_shell                   125973 non-null  int64
 14  su_attempted                 125973 non-null  int64
 15  num_root                     125973 non-null  int64
 16  num_file_creations           125973 non-null  int64
 17  num_shells                   125973 non-null  int64
 18  num_access_files             125973 non-null  int64
 19  num_outbound_cmds            125973 non-null  int64
 20  is_host_login                125973 non-null  int64
 21  is_guest_login               125973 non-null  int64
 22  count                        125973 non-null  int64
 23  srv_count                    125973 non-null  int64
 24  serror_rate                  125973 non-null  float64
 25  srv_serror_rate              125973 non-null  float64
 26  rerror_rate                  125973 non-null  float64
 27  srv_rerror_rate              125973 non-null  float64
 28  same_srv_rate                125973 non-null  float64
 29  diff_srv_rate                125973 non-null  float64
 30  srv_diff_host_rate           125973 non-null  float64
 31  dst_host_count               125973 non-null  int64
 32  dst_host_srv_count           125973 non-null  int64
 33  dst_host_same_srv_rate       125973 non-null  float64
 34  dst_host_diff_srv_rate       125973 non-null  float64
 35  dst_host_same_src_port_rate  125973 non-null  float64
 36  dst_host_srv_diff_host_rate  125973 non-null  float64
 37  dst_host_serror_rate         125973 non-null  float64
 38  dst_host_srv_serror_rate     125973 non-null  float64
 39  dst_host_rerror_rate         125973 non-null  float64
 40  dst_host_srv_rerror_rate     125973 non-null  float64
 41  attack                       125973 non-null  object
 42  level                        125973 non-null  int64
dtypes: float64(15), int64(24), object(4)
memory usage: 41.3+ MB
None
Unique attack types:
['normal' 'neptune' 'warezclient' 'ipsweep' 'portsweep' 'teardrop' 'nmap'
 'satan' 'smurf' 'pod' 'back' 'guess_passwd' 'ftp_write' 'multihop'
 'rootkit' 'buffer_overflow' 'imap' 'warezmaster' 'phf' 'land'
 'loadmodule' 'spy' 'perl']

In [5]:
# Define attack categories
attack_mapping = {
    'apache2': 'DoS', 'back': 'DoS', 'land': 'DoS', 'neptune': 'DoS', 'mailbomb': 'DoS',
    'pod': 'DoS', 'processtable': 'DoS', 'smurf': 'DoS', 'teardrop': 'DoS', 'udpstorm': 'DoS', 'worm': 'DoS',

    'ipsweep': 'Probe', 'mscan': 'Probe', 'nmap': 'Probe', 'portsweep': 'Probe', 'saint': 'Probe', 'satan': 'Probe',

    'buffer_overflow': 'Privilege Escalation', 'loadmodule': 'Privilege Escalation', 'perl': 'Privilege Escalation',
    'ps': 'Privilege Escalation', 'rootkit': 'Privilege Escalation', 'sqlattack': 'Privilege Escalation', 'xterm': 'Privilege Escalation',

    'ftp_write': 'Remote Access', 'guess_passwd': 'Remote Access', 'http_tunnel': 'Remote Access', 'imap': 'Remote Access',
    'multihop': 'Remote Access', 'named': 'Remote Access', 'phf': 'Remote Access', 'sendmail': 'Remote Access',
    'snmpgetattack': 'Remote Access', 'snmpguess': 'Remote Access', 'spy': 'Remote Access', 'warezclient': 'Remote Access',
    'warezmaster': 'Remote Access', 'xclock': 'Remote Access', 'xsnoop': 'Remote Access'
}

# Apply mapping
df['attack_category'] = df['attack'].map(attack_mapping).fillna('Normal')

# Display counts of each category
print(df['attack_category'].value_counts())

attack_category
Normal                  67343
DoS                     45927
Probe                   11656
Remote Access             995
Privilege Escalation       52
Name: count, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

# One-hot encode protocol_type, service, and flag
df = pd.get_dummies(df, columns=['protocol_type', 'service', 'flag'])

# Label encode attack_category
encoder = LabelEncoder()
df['attack_category_encoded'] = encoder.fit_transform(df['attack_category'])

# Drop old attack columns
df = df.drop(columns=['attack', 'attack_category'])

# Display first 5 rows
df.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH,attack_category_encoded
0,0,491,0,0,0,0,0,0,0,0,...,False,False,False,False,False,False,False,True,False,1
1,0,146,0,0,0,0,0,0,0,0,...,False,False,False,False,False,False,False,True,False,1
2,0,0,0,0,0,0,0,0,0,0,...,False,False,False,True,False,False,False,False,False,0
3,0,232,8153,0,0,0,0,0,1,0,...,False,False,False,False,False,False,False,True,False,1
4,0,199,420,0,0,0,0,0,1,0,...,False,False,False,False,False,False,False,True,False,1

In [7]:
from sklearn.preprocessing import MinMaxScaler

# Select numerical columns (excluding encoded attack_category)
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
numerical_cols.remove('attack_category_encoded')  # Exclude target

# Apply Min-Max Scaling
scaler = MinMaxScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

# Display first 5 rows
df.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH,attack_category_encoded
0,0.0,3.558064e-07,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,True,False,1
1,0.0,1.057999e-07,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,True,False,1
2,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,True,False,False,False,False,False,0
3,0.0,1.681203e-07,6.223962e-06,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,False,False,False,False,False,False,False,True,False,1
4,0.0,1.442067e-07,3.206260e-07,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,False,False,False,False,False,False,False,True,False,1

# Step 7: Splitting the Dataset
We'll now split the dataset into:

1) Training Set (80%) → Used to train the model
2) Testing Set (20%) → Used to evaluate the model's performance

In [9]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df.drop(columns=['attack_category_encoded'])  # Features
y = df['attack_category_encoded']  # Target labels

# Split the dataset (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Display dataset shapes
print(f"Training set shape: {X_train.shape}")
print(f"Testing set shape: {X_test.shape}")

Training set shape: (100778, 123)
Testing set shape: (25195, 123)

# Step 8: Model Selection & Training
Since we are building an AI-based Intrusion Detection System (IDS), we will experiment with different machine learning and deep learning models.

For a thorough approach, we’ll try:
1. Traditional ML models: Random Forest, SVM, etc.
2. Deep Learning models: Neural Networks (ANN), LSTMs, CNNs

## 8.1 Exploring Traditional ML models
## 8.1.1 Random Forest Classifier

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Initialize the model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

# Train the model
rf_model.fit(X_train, y_train)

# Make predictions
y_pred = rf_model.predict(X_test)

# Evaluate performance
accuracy_rfc = accuracy_score(y_test, y_pred)
print(f"Random Forest Accuracy: {accuracy_rfc:.4f}")

# Detailed classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Random Forest Accuracy: 0.9995

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9186
           1       1.00      1.00      1.00     13469
           2       1.00      0.90      0.95        10
           3       1.00      1.00      1.00      2331
           4       1.00      0.97      0.99       199

    accuracy                           1.00     25195
   macro avg       1.00      0.97      0.99     25195
weighted avg       1.00      1.00      1.00     25195

In [13]:
# Observations:
# Extremely high accuracy → Indicates strong classification performance
# High precision & recall → No significant false positives or false negatives
# Class Imbalance Noted → Some attack categories (e.g., Privilege Escalation) have fewer instances, affecting recall (0.90 for class 2).

## 8.1.2 Support Vector Machine

In [15]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Train the SVM model
svm_model = SVC(kernel='rbf', C=1.0, gamma='scale')
svm_model.fit(X_train, y_train)

# Predictions
y_pred_svm = svm_model.predict(X_test)

# Evaluation
svm_accuracy = accuracy_score(y_test, y_pred_svm)
print(f"SVM Accuracy: {svm_accuracy:.4f}")
print("Classification Report:\n", classification_report(y_test, y_pred_svm))

SVM Accuracy: 0.9973
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9186
           1       1.00      1.00      1.00     13469
           2       1.00      0.80      0.89        10
           3       0.99      1.00      0.99      2331
           4       0.92      0.97      0.95       199

    accuracy                           1.00     25195
   macro avg       0.98      0.95      0.97     25195
weighted avg       1.00      1.00      1.00     25195

## 8.1.3 KNN

In [17]:
from sklearn.neighbors import KNeighborsClassifier

# Train the KNN model
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Predictions
y_pred_knn = knn_model.predict(X_test)

# Evaluation
knn_accuracy = accuracy_score(y_test, y_pred_knn)
print(f"KNN Accuracy: {knn_accuracy:.4f}")
print("Classification Report:\n", classification_report(y_test, y_pred_knn))

KNN Accuracy: 0.9973
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9186
           1       1.00      1.00      1.00     13469
           2       0.78      0.70      0.74        10
           3       1.00      0.99      0.99      2331
           4       0.98      0.94      0.96       199

    accuracy                           1.00     25195
   macro avg       0.95      0.92      0.94     25195
weighted avg       1.00      1.00      1.00     25195

## 8.1.4 XGBoost

In [19]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\sujph\.conda\envs\myenv\lib\site-packages (2.1.4)
Requirement already satisfied: numpy in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from xgboost) (2.0.2)
Requirement already satisfied: scipy in c:\users\sujph\.conda\envs\myenv\lib\site-packages (from xgboost) (1.13.1)

In [20]:
from xgboost import XGBClassifier

# Train the XGBoost model
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train, y_train)

# Predictions
y_pred_xgb = xgb_model.predict(X_test)

# Evaluation
xgb_accuracy = accuracy_score(y_test, y_pred_xgb)
print(f"XGBoost Accuracy: {xgb_accuracy:.4f}")
print("Classification Report:\n", classification_report(y_test, y_pred_xgb))

C:\Users\sujph\.conda\envs\myenv\lib\site-packages\xgboost\core.py:158: UserWarning: [11:54:30] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBoost Accuracy: 0.9994
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9186
           1       1.00      1.00      1.00     13469
           2       0.90      0.90      0.90        10
           3       1.00      1.00      1.00      2331
           4       0.99      0.97      0.98       199

    accuracy                           1.00     25195
   macro avg       0.98      0.97      0.98     25195
weighted avg       1.00      1.00      1.00     25195

## 8.2 Deep Learning Approach

## 8.2.1 Artificial Neural Networks - ANN

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# Build the ANN model
ann_model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(5, activation='softmax')  # 5 output classes
])

# Compile the model
ann_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = ann_model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test))

# Evaluate the model
test_loss, test_acc_ann = ann_model.evaluate(X_test, y_test, verbose=0)
print(f"ANN Model Accuracy: {test_acc_ann:.4f}")

C:\Users\sujph\.conda\envs\myenv\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/10
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9289 - loss: 0.2326 - val_accuracy: 0.9938 - val_loss: 0.0164
Epoch 2/10
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9930 - loss: 0.0208 - val_accuracy: 0.9969 - val_loss: 0.0088
Epoch 3/10
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9952 - loss: 0.0141 - val_accuracy: 0.9975 - val_loss: 0.0082
Epoch 4/10
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9955 - loss: 0.0130 - val_accuracy: 0.9968 - val_loss: 0.0086
Epoch 5/10
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9962 - loss: 0.0111 - val_accuracy: 0.9982 - val_loss: 0.0057
Epoch 6/10
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9967 - loss: 0.0093 - val_accuracy: 0.9986 - val_loss: 0.0057
Epoch 7/10
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9970 - loss: 0.0088 - val_accuracy: 0.9977 - val_loss: 0.0064
Epoch 8/10
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9975 - loss: 0.0074 - val_accuracy: 0.9977 - val_loss: 0.0069
Epoch 9/10
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9973 - loss: 0.0075 - val_accuracy: 0.9983 - val_loss: 0.0063
Epoch 10/10
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9975 - loss: 0.0080 - val_accuracy: 0.9985 - val_loss: 0.0049
ANN Model Accuracy: 0.9985

In [24]:
# Observations
# Both models perform exceptionally well
# ANN generalizes well and improves with more data
# Random Forest slightly outperforms, but may overfit in some cases

## 8.2.2 Convolutional Neural Networks (CNN)

In [26]:
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Split dataset into features and labels
X = df.drop(columns=["attack_category_encoded"]).values
y = df["attack_category_encoded"].values

# Normalize the input features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Reshape input for CNN (samples, timesteps, features) -> (samples, features, 1)
X = X.reshape(X.shape[0], X.shape[1], 1)

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert labels to categorical format (One-hot encoding)
num_classes = len(np.unique(y))
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

# Build CNN Model
cnn_model = Sequential([
    Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),
    Dropout(0.5),

    Conv1D(filters=128, kernel_size=3, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),
    Dropout(0.6),

    Flatten(),
    Dense(128, activation='relu', kernel_regularizer=keras.regularizers.l2(0.01)),
    Dropout(0.6),
    Dense(num_classes, activation='softmax')
])

# Compile Model
cnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Add Early Stopping
early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# Train Model with Early Stopping
history = cnn_model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test), callbacks=[early_stop])

# Evaluate Model
test_loss, test_acc_cnn = cnn_model.evaluate(X_test, y_test)
print(f"Improved CNN Model Accuracy: {test_acc_cnn:.4f}")

Epoch 1/20

C:\Users\sujph\.conda\envs\myenv\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

3150/3150 ━━━━━━━━━━━━━━━━━━━━ 41s 12ms/step - accuracy: 0.9351 - loss: 1.2411 - val_accuracy: 0.9895 - val_loss: 0.3759
Epoch 2/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 37s 12ms/step - accuracy: 0.9748 - loss: 0.3963 - val_accuracy: 0.9903 - val_loss: 0.3141
Epoch 3/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 46s 14ms/step - accuracy: 0.9789 - loss: 0.3408 - val_accuracy: 0.9875 - val_loss: 0.3017
Epoch 4/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 43s 14ms/step - accuracy: 0.9802 - loss: 0.3249 - val_accuracy: 0.9893 - val_loss: 0.3025
Epoch 5/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 42s 13ms/step - accuracy: 0.9804 - loss: 0.3151 - val_accuracy: 0.9915 - val_loss: 0.3069
Epoch 6/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 42s 13ms/step - accuracy: 0.9807 - loss: 0.3130 - val_accuracy: 0.9919 - val_loss: 0.2665
Epoch 7/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 42s 13ms/step - accuracy: 0.9820 - loss: 0.2969 - val_accuracy: 0.9904 - val_loss: 0.2738
Epoch 8/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 43s 14ms/step - accuracy: 0.9814 - loss: 0.2857 - val_accuracy: 0.9915 - val_loss: 0.2489
Epoch 9/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 46s 14ms/step - accuracy: 0.9827 - loss: 0.2792 - val_accuracy: 0.9929 - val_loss: 0.2485
Epoch 10/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 49s 16ms/step - accuracy: 0.9815 - loss: 0.2840 - val_accuracy: 0.9911 - val_loss: 0.2722
Epoch 11/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 53s 17ms/step - accuracy: 0.9829 - loss: 0.2729 - val_accuracy: 0.9915 - val_loss: 0.2177
Epoch 12/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 48s 15ms/step - accuracy: 0.9833 - loss: 0.2583 - val_accuracy: 0.9921 - val_loss: 0.2234
Epoch 13/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 49s 15ms/step - accuracy: 0.9834 - loss: 0.2594 - val_accuracy: 0.9918 - val_loss: 0.1977
Epoch 14/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 60s 19ms/step - accuracy: 0.9830 - loss: 0.2559 - val_accuracy: 0.9922 - val_loss: 0.2096
Epoch 15/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 46s 15ms/step - accuracy: 0.9829 - loss: 0.2432 - val_accuracy: 0.9927 - val_loss: 0.1974
Epoch 16/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 43s 14ms/step - accuracy: 0.9829 - loss: 0.2471 - val_accuracy: 0.9920 - val_loss: 0.1955
Epoch 17/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 45s 14ms/step - accuracy: 0.9834 - loss: 0.2384 - val_accuracy: 0.9917 - val_loss: 0.1853
Epoch 18/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 45s 14ms/step - accuracy: 0.9829 - loss: 0.2315 - val_accuracy: 0.9931 - val_loss: 0.1957
Epoch 19/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 43s 14ms/step - accuracy: 0.9833 - loss: 0.2294 - val_accuracy: 0.9933 - val_loss: 0.1805
Epoch 20/20
3150/3150 ━━━━━━━━━━━━━━━━━━━━ 43s 14ms/step - accuracy: 0.9836 - loss: 0.2238 - val_accuracy: 0.9914 - val_loss: 0.2156
788/788 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9927 - loss: 0.1772
Improved CNN Model Accuracy: 0.9933

## 8.2.3 Recurrent Neural Networks (RNN) & Long Short-Term Memory (LSTM)

## Implementing Basic RNN Model

In [29]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Reshape data for RNN (samples, timesteps=1, features)
X_train_rnn = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test_rnn = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))

# Build RNN Model
rnn_model = Sequential([
    SimpleRNN(128, activation='relu', return_sequences=True, input_shape=(1, X_train.shape[1])),
    Dropout(0.2),
    SimpleRNN(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(y_train.shape[1], activation='softmax')  # Multi-class classification
])

# Compile Model
rnn_model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Train RNN Model
rnn_history = rnn_model.fit(X_train_rnn, y_train, validation_data=(X_test_rnn, y_test), epochs=20, batch_size=64)

Epoch 1/20

C:\Users\sujph\.conda\envs\myenv\lib\site-packages\keras\src\layers\rnn\rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

1575/1575 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9461 - loss: 0.1818 - val_accuracy: 0.9934 - val_loss: 0.0227
Epoch 2/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9940 - loss: 0.0212 - val_accuracy: 0.9952 - val_loss: 0.0224
Epoch 3/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9955 - loss: 0.0137 - val_accuracy: 0.9952 - val_loss: 0.0233
Epoch 4/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9962 - loss: 0.0126 - val_accuracy: 0.9955 - val_loss: 0.0250
Epoch 5/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9968 - loss: 0.0099 - val_accuracy: 0.9966 - val_loss: 0.0210
Epoch 6/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9971 - loss: 0.0087 - val_accuracy: 0.9965 - val_loss: 0.0198
Epoch 7/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9970 - loss: 0.0083 - val_accuracy: 0.9970 - val_loss: 0.0188
Epoch 8/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9975 - loss: 0.0072 - val_accuracy: 0.9965 - val_loss: 0.0216
Epoch 9/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9977 - loss: 0.0072 - val_accuracy: 0.9962 - val_loss: 0.0192
Epoch 10/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9981 - loss: 0.0064 - val_accuracy: 0.9979 - val_loss: 0.0213
Epoch 11/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9982 - loss: 0.0051 - val_accuracy: 0.9969 - val_loss: 0.0171
Epoch 12/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9983 - loss: 0.0045 - val_accuracy: 0.9966 - val_loss: 0.0303
Epoch 13/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9981 - loss: 0.0048 - val_accuracy: 0.9973 - val_loss: 0.0300
Epoch 14/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9983 - loss: 0.0097 - val_accuracy: 0.9970 - val_loss: 0.0297
Epoch 15/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9988 - loss: 0.0041 - val_accuracy: 0.9983 - val_loss: 0.0286
Epoch 16/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9984 - loss: 0.0046 - val_accuracy: 0.9982 - val_loss: 0.0220
Epoch 17/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9984 - loss: 0.0050 - val_accuracy: 0.9980 - val_loss: 0.0187
Epoch 18/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9982 - loss: 0.0045 - val_accuracy: 0.9982 - val_loss: 0.0265
Epoch 19/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9985 - loss: 0.0043 - val_accuracy: 0.9981 - val_loss: 0.0285
Epoch 20/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9985 - loss: 0.0045 - val_accuracy: 0.9971 - val_loss: 0.0331

## Implementing LSTM Model

In [31]:
from tensorflow.keras.layers import LSTM

# Build LSTM Model
lstm_model = Sequential([
    LSTM(128, activation='tanh', return_sequences=True, input_shape=(1, X_train.shape[1])),
    Dropout(0.2),
    LSTM(64, activation='tanh'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(y_train.shape[1], activation='softmax')  # Multi-class classification
])

# Compile Model
lstm_model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Train LSTM Model
lstm_history = lstm_model.fit(X_train_rnn, y_train, validation_data=(X_test_rnn, y_test), epochs=20, batch_size=64)

Epoch 1/20

C:\Users\sujph\.conda\envs\myenv\lib\site-packages\keras\src\layers\rnn\rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

1575/1575 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9621 - loss: 0.2039 - val_accuracy: 0.9943 - val_loss: 0.0161
Epoch 2/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9955 - loss: 0.0127 - val_accuracy: 0.9962 - val_loss: 0.0143
Epoch 3/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9969 - loss: 0.0095 - val_accuracy: 0.9950 - val_loss: 0.0150
Epoch 4/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9971 - loss: 0.0078 - val_accuracy: 0.9963 - val_loss: 0.0131
Epoch 5/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9978 - loss: 0.0058 - val_accuracy: 0.9971 - val_loss: 0.0121
Epoch 6/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9980 - loss: 0.0054 - val_accuracy: 0.9945 - val_loss: 0.0217
Epoch 7/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9981 - loss: 0.0052 - val_accuracy: 0.9968 - val_loss: 0.0121
Epoch 8/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9981 - loss: 0.0051 - val_accuracy: 0.9979 - val_loss: 0.0110
Epoch 9/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9982 - loss: 0.0044 - val_accuracy: 0.9979 - val_loss: 0.0109
Epoch 10/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9987 - loss: 0.0041 - val_accuracy: 0.9972 - val_loss: 0.0126
Epoch 11/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9985 - loss: 0.0037 - val_accuracy: 0.9979 - val_loss: 0.0111
Epoch 12/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9986 - loss: 0.0041 - val_accuracy: 0.9983 - val_loss: 0.0101
Epoch 13/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9985 - loss: 0.0040 - val_accuracy: 0.9983 - val_loss: 0.0104
Epoch 14/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9988 - loss: 0.0035 - val_accuracy: 0.9980 - val_loss: 0.0102
Epoch 15/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9988 - loss: 0.0031 - val_accuracy: 0.9981 - val_loss: 0.0116
Epoch 16/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9989 - loss: 0.0031 - val_accuracy: 0.9980 - val_loss: 0.0118
Epoch 17/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9991 - loss: 0.0025 - val_accuracy: 0.9980 - val_loss: 0.0111
Epoch 18/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9988 - loss: 0.0027 - val_accuracy: 0.9981 - val_loss: 0.0112
Epoch 19/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9990 - loss: 0.0028 - val_accuracy: 0.9980 - val_loss: 0.0119
Epoch 20/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9988 - loss: 0.0031 - val_accuracy: 0.9973 - val_loss: 0.0121

In [32]:
# Evaluate RNN Model
rnn_loss, rnn_acc = rnn_model.evaluate(X_test_rnn, y_test)
print(f"RNN Model Accuracy: {rnn_acc:.4f}")

# Evaluate LSTM Model
lstm_loss, lstm_acc = lstm_model.evaluate(X_test_rnn, y_test)
print(f"LSTM Model Accuracy: {lstm_acc:.4f}")

788/788 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9972 - loss: 0.0242
RNN Model Accuracy: 0.9971
788/788 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9975 - loss: 0.0112
LSTM Model Accuracy: 0.9973

## Implementing GRU Model

In [34]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Define GRU model
gru_model = Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1], 1)),  # Input layer
    GRU(64, return_sequences=True, activation='relu'),
    Dropout(0.2),
    GRU(32, activation='relu'),
    Dropout(0.2),
    Dense(16, activation='relu'),
    Dense(y_train.shape[1], activation='softmax')  # Output layer for classification
])

# Compile the model
gru_model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = gru_model.fit(X_train, y_train, epochs=20, batch_size=64, validation_data=(X_test, y_test), verbose=1)

# Evaluate on test data
test_loss, test_accuracy_gru = gru_model.evaluate(X_test, y_test)
print(f"GRU Model Accuracy: {test_accuracy_gru:.4f}")

Epoch 1/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 157s 97ms/step - accuracy: 0.7837 - loss: 0.6624 - val_accuracy: 0.9236 - val_loss: 0.2277
Epoch 2/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 143s 91ms/step - accuracy: 0.9215 - loss: 0.2234 - val_accuracy: 0.9296 - val_loss: 0.1860
Epoch 3/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 142s 90ms/step - accuracy: 0.9468 - loss: 0.1637 - val_accuracy: 0.9534 - val_loss: 0.1234
Epoch 4/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 142s 90ms/step - accuracy: 0.9506 - loss: 0.1472 - val_accuracy: 0.9494 - val_loss: 0.1757
Epoch 5/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 150s 95ms/step - accuracy: 0.9572 - loss: 0.1511 - val_accuracy: 0.9713 - val_loss: 0.0959
Epoch 6/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 136s 86ms/step - accuracy: 0.9700 - loss: 0.1037 - val_accuracy: 0.9769 - val_loss: 0.0750
Epoch 7/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 116s 73ms/step - accuracy: 0.9730 - loss: 0.0968 - val_accuracy: 0.9770 - val_loss: 0.0764
Epoch 8/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 115s 73ms/step - accuracy: 0.9787 - loss: 0.0748 - val_accuracy: 0.9821 - val_loss: 0.0640
Epoch 9/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 119s 76ms/step - accuracy: 0.9813 - loss: 0.0685 - val_accuracy: 0.9825 - val_loss: 0.0624
Epoch 10/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 134s 85ms/step - accuracy: 0.9833 - loss: 0.0589 - val_accuracy: 0.9867 - val_loss: 0.0492
Epoch 11/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 133s 85ms/step - accuracy: 0.9860 - loss: 0.0510 - val_accuracy: 0.9890 - val_loss: 0.0409
Epoch 12/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 133s 84ms/step - accuracy: 0.9854 - loss: 0.0493 - val_accuracy: 0.9890 - val_loss: 0.0405
Epoch 13/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 134s 85ms/step - accuracy: 0.9870 - loss: 0.0436 - val_accuracy: 0.9871 - val_loss: 0.0429
Epoch 14/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 139s 88ms/step - accuracy: 0.9861 - loss: 0.0465 - val_accuracy: 0.9885 - val_loss: 0.0393
Epoch 15/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 137s 87ms/step - accuracy: 0.9854 - loss: 0.0488 - val_accuracy: 0.9888 - val_loss: 0.0376
Epoch 16/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 133s 84ms/step - accuracy: 0.9877 - loss: 0.0402 - val_accuracy: 0.9910 - val_loss: 0.0321
Epoch 17/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 134s 85ms/step - accuracy: 0.9671 - loss: 0.1057 - val_accuracy: 0.9906 - val_loss: 0.0352
Epoch 18/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 143s 85ms/step - accuracy: 0.9895 - loss: 0.0380 - val_accuracy: 0.9918 - val_loss: 0.0291
Epoch 19/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 135s 85ms/step - accuracy: 0.9899 - loss: 0.0368 - val_accuracy: 0.9926 - val_loss: 0.0299
Epoch 20/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 133s 85ms/step - accuracy: 0.9903 - loss: 0.0339 - val_accuracy: 0.9911 - val_loss: 0.0311
788/788 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - accuracy: 0.9910 - loss: 0.0331
GRU Model Accuracy: 0.9911

## 8.3 Hybrid Model (CNN + LSTM)
# We'll use CNN for feature extraction and LSTM for sequential learning.

In [56]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Dropout, BatchNormalization

# Define the CNN + LSTM model
model = Sequential([
    # CNN Block
    Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    Conv1D(filters=128, kernel_size=3, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    Conv1D(filters=256, kernel_size=3, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    # Ensure correct LSTM input shape
    LSTM(64, return_sequences=True),
    Dropout(0.3),
    LSTM(32),

    # Fully Connected Layer
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')  # Adjust for binary classification if needed
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Print model summary
model.summary()

C:\Users\sujph\.conda\envs\myenv\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 121, 64)        │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 121, 64)        │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 60, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 58, 128)        │        24,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 58, 128)        │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 29, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_4 (Conv1D)               │ (None, 27, 256)        │        98,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 27, 256)        │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_4 (MaxPooling1D)  │ (None, 13, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 13, 64)         │        82,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_11 (Dropout)            │ (None, 13, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 128)            │         4,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_12 (Dropout)            │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 5)              │           325 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 232,709 (909.02 KB)

 Trainable params: 231,813 (905.52 KB)

 Non-trainable params: 896 (3.50 KB)

In [58]:
# Define batch size and epochs
batch_size = 64
epochs = 20  # Adjust based on performance

# Train the model
history = model.fit(X_train, y_train, 
                    validation_data=(X_test, y_test), 
                    epochs=epochs, 
                    batch_size=batch_size)

Epoch 1/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 55s 32ms/step - accuracy: 0.9584 - loss: 0.1241 - val_accuracy: 0.9937 - val_loss: 0.0186
Epoch 2/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 51s 32ms/step - accuracy: 0.9932 - loss: 0.0212 - val_accuracy: 0.9933 - val_loss: 0.0238
Epoch 3/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 55s 35ms/step - accuracy: 0.9950 - loss: 0.0146 - val_accuracy: 0.9946 - val_loss: 0.0152
Epoch 4/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 54s 34ms/step - accuracy: 0.9956 - loss: 0.0131 - val_accuracy: 0.9937 - val_loss: 0.0219
Epoch 5/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 54s 34ms/step - accuracy: 0.9969 - loss: 0.0098 - val_accuracy: 0.9954 - val_loss: 0.0136
Epoch 6/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 59s 38ms/step - accuracy: 0.9965 - loss: 0.0110 - val_accuracy: 0.9943 - val_loss: 0.0214
Epoch 7/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 60s 38ms/step - accuracy: 0.9962 - loss: 0.0118 - val_accuracy: 0.9961 - val_loss: 0.0133
Epoch 8/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 59s 38ms/step - accuracy: 0.9973 - loss: 0.0079 - val_accuracy: 0.9963 - val_loss: 0.0119
Epoch 9/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 59s 37ms/step - accuracy: 0.9973 - loss: 0.0085 - val_accuracy: 0.9975 - val_loss: 0.0086
Epoch 10/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 61s 39ms/step - accuracy: 0.9978 - loss: 0.0070 - val_accuracy: 0.9971 - val_loss: 0.0111
Epoch 11/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 63s 40ms/step - accuracy: 0.9979 - loss: 0.0064 - val_accuracy: 0.9638 - val_loss: 0.3297
Epoch 12/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 53s 33ms/step - accuracy: 0.9978 - loss: 0.0070 - val_accuracy: 0.9979 - val_loss: 0.0085
Epoch 13/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 55s 35ms/step - accuracy: 0.9979 - loss: 0.0073 - val_accuracy: 0.9974 - val_loss: 0.0130
Epoch 14/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 56s 35ms/step - accuracy: 0.9981 - loss: 0.0064 - val_accuracy: 0.9971 - val_loss: 0.0127
Epoch 15/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 52s 33ms/step - accuracy: 0.9979 - loss: 0.0073 - val_accuracy: 0.9972 - val_loss: 0.0109
Epoch 16/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 51s 32ms/step - accuracy: 0.9982 - loss: 0.0061 - val_accuracy: 0.9977 - val_loss: 0.0103
Epoch 17/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 51s 32ms/step - accuracy: 0.9983 - loss: 0.0051 - val_accuracy: 0.9971 - val_loss: 0.0125
Epoch 18/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 51s 33ms/step - accuracy: 0.9982 - loss: 0.0069 - val_accuracy: 0.9974 - val_loss: 0.0103
Epoch 19/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 52s 33ms/step - accuracy: 0.9984 - loss: 0.0052 - val_accuracy: 0.9978 - val_loss: 0.0098
Epoch 20/20
1575/1575 ━━━━━━━━━━━━━━━━━━━━ 54s 34ms/step - accuracy: 0.9984 - loss: 0.0047 - val_accuracy: 0.9975 - val_loss: 0.0095

In [60]:
# Print final training and validation accuracy
train_acc = history.history['accuracy'][-1]  # Last epoch's accuracy
val_acc = history.history['val_accuracy'][-1]  # Last epoch's validation accuracy

print(f"Final Training Accuracy: {train_acc:.4f}")
print(f"Final Validation Accuracy: {val_acc:.4f}")

Final Training Accuracy: 0.9985
Final Validation Accuracy: 0.9975

In [62]:
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=1)
print(f"Test Accuracy: {test_acc:.4f}")

788/788 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9975 - loss: 0.0080
Test Accuracy: 0.9975

In [64]:
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Predict classes
y_pred = np.argmax(model.predict(X_test), axis=1)
y_true = np.argmax(y_test, axis=1)

# Print confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))

# Print classification report
print("\nClassification Report:\n", classification_report(y_true, y_pred))

788/788 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step
Confusion Matrix:
 [[ 9170     8     0     3     0]
 [    1 13409     3     9     0]
 [    0     6     4     1     0]
 [    1    11     0  2344     1]
 [    0    20     0     0   204]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      9181
           1       1.00      1.00      1.00     13422
           2       0.57      0.36      0.44        11
           3       0.99      0.99      0.99      2357
           4       1.00      0.91      0.95       224

    accuracy                           1.00     25195
   macro avg       0.91      0.85      0.88     25195
weighted avg       1.00      1.00      1.00     25195

In [66]:
model.save("nids_model.keras")
print("Model saved successfully!")

Model saved successfully!